# 应用名称
spring:
  application:
    name: sqliteDemo
  servlet:
    multipart:
      max-request-size: 100000MB
      max-file-size: 10000MB
      enabled: true
  thymeleaf:
    #关闭模板缓存(默认为true)
    cache: false
    #模板编码
#    encoding: utf-8
#    #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
#    prefix: classpath:/templates/
#    #在构建URL时添加到视图名称后的后缀（默认值：.html）
#    suffix: .html
#    mode: HTML5
#    check-template-location: true
#    content-type: text/html
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:E:\test\sqliteDemo\sql.db
    username:
    password:

server:
  port: 9257

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
  typeAliasesPackage: com.yxjr.**.entity



#文件上传路径 linux /home/weblogic/yxjrApp/upgrade/      windows D:/update/
uploadpacketPath: D:/update/

  #日志上传路径 linux /home/weblogic/yxjrApp/Logs/  windows D:/update/Logs/
logPath: D:/update/Logs/
